# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6a63904467b6962bc39a11c732cd9662585902dba37f5e619e5c49c3afc94aa615f50f4fbb51b6460c8ed8b148f420f68d57334c1c86398f1036023c3dab01f5

test:
  secret_key_base: 6e5b33b07b4c1ccc601c5f85c42afd576a65a26ec3dda2e16b08a80cec08b476812a8e51e98ad02db81fee4f7730f9b0e96117385768f4885eac3db3fd7b1481

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
